idf_component_register(
    SRCS
        "main.c"
        "smoke_test.c"
    INCLUDE_DIRS "."
    REQUIRES
        nvs_flash
        esp_wifi
        esp_event
        esp_netif
        esp_http_server
        esp_psram
        esp_timer
        driver
        esp32-camera
        servo_pwm
        task_ptz
        motor_l298n
        task_navigation
        task_sensor_fusion
        mpu6050
        audio_i2s
        task_audio
        sim800l
        task_sos
        battery
        ir_dock
        task_dock
        ssd1306
        task_oled
        task_behavior
        robot_mqtt
        self_test
)
